# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rtf}
  s.version = "0.4.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Wood", "Claudio Bustos", "Marcello Barnaba"]
  s.date = %q{2011-06-08}
  s.description = %q{Ruby RTF is a library that can be used to create rich text format (RTF) documents. RTF is a text based standard for laying out document content.}
  s.email = %q{m.barnaba@ifad.org}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = `git ls-files`.split("\n")
  s.homepage = %q{http://github.com/ifad/rtf}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ruby-statsample}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby library to create rich text format documents.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.1"])
      s.add_runtime_dependency(%q<tidy-ext>, ["~> 0.1"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.1"])
      s.add_dependency(%q<tidy-ext>, ["~> 0.1"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.1"])
    s.add_dependency(%q<tidy-ext>, ["~> 0.1"])
  end
end

